# Generated by Django 4.2.8 on 2024-09-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empower360', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
