# Generated by Django 4.2.8 on 2024-09-11 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiring_position', models.CharField(max_length=150)),
                ('job_type', models.CharField(max_length=150)),
                ('reporting_to', models.CharField(default='', max_length=150)),
                ('num_of_vac', models.IntegerField(default=0)),
                ('reason_for', models.CharField(default='', max_length=150)),
                ('gender', models.CharField(default='', max_length=150)),
                ('career_level', models.CharField(default='', max_length=150)),
                ('year_of_ex', models.CharField(default='', max_length=150)),
                ('edu_level', models.CharField(default='', max_length=150)),
                ('edu_major', models.CharField(default='', max_length=150)),
                ('required_cert', models.CharField(default='', max_length=150)),
                ('eng_level', models.CharField(default='', max_length=150)),
                ('microsoft_level', models.CharField(default='', max_length=150)),
                ('status', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiring_form', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HR_HiringForm',
            },
        ),
    ]
